language: python
python:
  - "3.6"
install:
  - python setup.py install

script:
  - python setup.py test

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=smetj/wishbone
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT --build-arg branch=$TRAVIS_BRANCH .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker push $REPO:$TAG
  - docker push $REPO:$TRAVIS_COMMIT

notifications:
  webhooks:
    urls:
      - https://$WEBHOOK_USER:$WEBHOOK_PASSWORD@events.smetj.net/travis
    on_success: always # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
